language: bash
sudo: required
services:
  - docker

before_install:
  - docker pull golang:1.7.5
  - docker pull node:6.11.0-slim
  - docker pull f5devcentral/containthedocs

script:
  - set -e
  - if [ "$DOCKER_NAMESPACE" == "" ]; then DOCKER_NAMESPACE="local"; fi
  - BASE_PUSH_TARGET="$DOCKER_NAMESPACE/cf-bigip-ctlr"
  - |
    if [ "$DOCKER_P" == "" -o "$DOCKER_U" == "" -o $DOCKER_NAMESPACE == "" ]; then
      echo "[INFO] Docker user, password, or namespace vars absent from travis-ci."
      echo "[INFO] See DEVEL.md section 'Travis Builds' to configure travis with DockerHub."
    else
      docker login -u="$DOCKER_U" -p="$DOCKER_P"
      DOCKER_READY="true"
    fi
  - export IMG_TAG="${BASE_PUSH_TARGET}:${TRAVIS_COMMIT}"
  - export BUILD_IMG_TAG="${BASE_PUSH_TARGET}-devel:${TRAVIS_COMMIT}"
  - export CLEAN_BUILD=true
  - export BASE_OS=alpine
  - ./build-tools/build-devel-image.sh
  - ./build-tools/run-in-docker.sh make verify
  - ./build-tools/build-debug-artifacts.sh
  - ./build-tools/build-release-artifacts.sh
  - ./build-tools/build-release-images.sh
  - docker tag "$IMG_TAG" "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH"
  - docker tag "$IMG_TAG" "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH-n-$TRAVIS_BUILD_NUMBER-id-$TRAVIS_BUILD_ID"
  - |
    if [ "$DOCKER_READY" ]; then
      docker push "$IMG_TAG"
      docker push "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH"
      docker push "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH-n-$TRAVIS_BUILD_NUMBER-id-$TRAVIS_BUILD_ID"
    fi

