#!/bin/bash
set -e -x

GINKGO_OPTIONS=$@

function printStatus {
  if [ $? -eq 0 ]; then
    echo -e "\nSWEET SUITE SUCCESS"
  else
    echo -e "\nSUITE FAILURE"
  fi
}

trap printStatus EXIT

tmpdir=$(mktemp -d)

if uname -a | grep Darwin; then OS=darwin; else OS=linux; fi

GINKGO_FLAGS="ginkgo ${GINKGO_OPTIONS} -r -keepGoing -p -trace -randomizeAllSpecs -progress  --nodes 4"

export PATH=$PATH:$PWD/bin
go get github.com/nats-io/gnatsd
go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

$GINKGO_FLAGS "${GOPATH}/src/github.com/cf-bigip-ctlr"

if [ "$OS" == linux ]; then
  rm -rf $GOPATH/bin/{gnatsd,ginkgo,etcd}
fi
