// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/F5Networks/cf-bigip-ctlr/f5router"
	"github.com/F5Networks/cf-bigip-ctlr/f5router/routeUpdate"
	"github.com/F5Networks/cf-bigip-ctlr/servicebroker/planResources"
)

type FakeRouter struct {
	AddPlansStub        func(plans map[string]planResources.Plan)
	addPlansMutex       sync.RWMutex
	addPlansArgsForCall []struct {
		plans map[string]planResources.Plan
	}
	VerifyPlanExistsStub        func(planID string) error
	verifyPlanExistsMutex       sync.RWMutex
	verifyPlanExistsArgsForCall []struct {
		planID string
	}
	verifyPlanExistsReturns struct {
		result1 error
	}
	verifyPlanExistsReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateRouteStub        func(ru routeUpdate.RouteUpdate)
	updateRouteMutex       sync.RWMutex
	updateRouteArgsForCall []struct {
		ru routeUpdate.RouteUpdate
	}
	AddBindIDRouteURIPlanNameMappingStub        func(bindID, routeURI, planID string)
	addBindIDRouteURIPlanNameMappingMutex       sync.RWMutex
	addBindIDRouteURIPlanNameMappingArgsForCall []struct {
		bindID   string
		routeURI string
		planID   string
	}
	RemoveBindIDRouteURIPlanNameMappingStub        func(bindID string)
	removeBindIDRouteURIPlanNameMappingMutex       sync.RWMutex
	removeBindIDRouteURIPlanNameMappingArgsForCall []struct {
		bindID string
	}
	GetRouteURIFromBindIDStub        func(bindID string) string
	getRouteURIFromBindIDMutex       sync.RWMutex
	getRouteURIFromBindIDArgsForCall []struct {
		bindID string
	}
	getRouteURIFromBindIDReturns struct {
		result1 string
	}
	getRouteURIFromBindIDReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRouter) AddPlans(plans map[string]planResources.Plan) {
	fake.addPlansMutex.Lock()
	fake.addPlansArgsForCall = append(fake.addPlansArgsForCall, struct {
		plans map[string]planResources.Plan
	}{plans})
	fake.recordInvocation("AddPlans", []interface{}{plans})
	fake.addPlansMutex.Unlock()
	if fake.AddPlansStub != nil {
		fake.AddPlansStub(plans)
	}
}

func (fake *FakeRouter) AddPlansCallCount() int {
	fake.addPlansMutex.RLock()
	defer fake.addPlansMutex.RUnlock()
	return len(fake.addPlansArgsForCall)
}

func (fake *FakeRouter) AddPlansArgsForCall(i int) map[string]planResources.Plan {
	fake.addPlansMutex.RLock()
	defer fake.addPlansMutex.RUnlock()
	return fake.addPlansArgsForCall[i].plans
}

func (fake *FakeRouter) VerifyPlanExists(planID string) error {
	fake.verifyPlanExistsMutex.Lock()
	ret, specificReturn := fake.verifyPlanExistsReturnsOnCall[len(fake.verifyPlanExistsArgsForCall)]
	fake.verifyPlanExistsArgsForCall = append(fake.verifyPlanExistsArgsForCall, struct {
		planID string
	}{planID})
	fake.recordInvocation("VerifyPlanExists", []interface{}{planID})
	fake.verifyPlanExistsMutex.Unlock()
	if fake.VerifyPlanExistsStub != nil {
		return fake.VerifyPlanExistsStub(planID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.verifyPlanExistsReturns.result1
}

func (fake *FakeRouter) VerifyPlanExistsCallCount() int {
	fake.verifyPlanExistsMutex.RLock()
	defer fake.verifyPlanExistsMutex.RUnlock()
	return len(fake.verifyPlanExistsArgsForCall)
}

func (fake *FakeRouter) VerifyPlanExistsArgsForCall(i int) string {
	fake.verifyPlanExistsMutex.RLock()
	defer fake.verifyPlanExistsMutex.RUnlock()
	return fake.verifyPlanExistsArgsForCall[i].planID
}

func (fake *FakeRouter) VerifyPlanExistsReturns(result1 error) {
	fake.VerifyPlanExistsStub = nil
	fake.verifyPlanExistsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRouter) VerifyPlanExistsReturnsOnCall(i int, result1 error) {
	fake.VerifyPlanExistsStub = nil
	if fake.verifyPlanExistsReturnsOnCall == nil {
		fake.verifyPlanExistsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyPlanExistsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRouter) UpdateRoute(ru routeUpdate.RouteUpdate) {
	fake.updateRouteMutex.Lock()
	fake.updateRouteArgsForCall = append(fake.updateRouteArgsForCall, struct {
		ru routeUpdate.RouteUpdate
	}{ru})
	fake.recordInvocation("UpdateRoute", []interface{}{ru})
	fake.updateRouteMutex.Unlock()
	if fake.UpdateRouteStub != nil {
		fake.UpdateRouteStub(ru)
	}
}

func (fake *FakeRouter) UpdateRouteCallCount() int {
	fake.updateRouteMutex.RLock()
	defer fake.updateRouteMutex.RUnlock()
	return len(fake.updateRouteArgsForCall)
}

func (fake *FakeRouter) UpdateRouteArgsForCall(i int) routeUpdate.RouteUpdate {
	fake.updateRouteMutex.RLock()
	defer fake.updateRouteMutex.RUnlock()
	return fake.updateRouteArgsForCall[i].ru
}

func (fake *FakeRouter) AddBindIDRouteURIPlanNameMapping(bindID string, routeURI string, planID string) {
	fake.addBindIDRouteURIPlanNameMappingMutex.Lock()
	fake.addBindIDRouteURIPlanNameMappingArgsForCall = append(fake.addBindIDRouteURIPlanNameMappingArgsForCall, struct {
		bindID   string
		routeURI string
		planID   string
	}{bindID, routeURI, planID})
	fake.recordInvocation("AddBindIDRouteURIPlanNameMapping", []interface{}{bindID, routeURI, planID})
	fake.addBindIDRouteURIPlanNameMappingMutex.Unlock()
	if fake.AddBindIDRouteURIPlanNameMappingStub != nil {
		fake.AddBindIDRouteURIPlanNameMappingStub(bindID, routeURI, planID)
	}
}

func (fake *FakeRouter) AddBindIDRouteURIPlanNameMappingCallCount() int {
	fake.addBindIDRouteURIPlanNameMappingMutex.RLock()
	defer fake.addBindIDRouteURIPlanNameMappingMutex.RUnlock()
	return len(fake.addBindIDRouteURIPlanNameMappingArgsForCall)
}

func (fake *FakeRouter) AddBindIDRouteURIPlanNameMappingArgsForCall(i int) (string, string, string) {
	fake.addBindIDRouteURIPlanNameMappingMutex.RLock()
	defer fake.addBindIDRouteURIPlanNameMappingMutex.RUnlock()
	return fake.addBindIDRouteURIPlanNameMappingArgsForCall[i].bindID, fake.addBindIDRouteURIPlanNameMappingArgsForCall[i].routeURI, fake.addBindIDRouteURIPlanNameMappingArgsForCall[i].planID
}

func (fake *FakeRouter) RemoveBindIDRouteURIPlanNameMapping(bindID string) {
	fake.removeBindIDRouteURIPlanNameMappingMutex.Lock()
	fake.removeBindIDRouteURIPlanNameMappingArgsForCall = append(fake.removeBindIDRouteURIPlanNameMappingArgsForCall, struct {
		bindID string
	}{bindID})
	fake.recordInvocation("RemoveBindIDRouteURIPlanNameMapping", []interface{}{bindID})
	fake.removeBindIDRouteURIPlanNameMappingMutex.Unlock()
	if fake.RemoveBindIDRouteURIPlanNameMappingStub != nil {
		fake.RemoveBindIDRouteURIPlanNameMappingStub(bindID)
	}
}

func (fake *FakeRouter) RemoveBindIDRouteURIPlanNameMappingCallCount() int {
	fake.removeBindIDRouteURIPlanNameMappingMutex.RLock()
	defer fake.removeBindIDRouteURIPlanNameMappingMutex.RUnlock()
	return len(fake.removeBindIDRouteURIPlanNameMappingArgsForCall)
}

func (fake *FakeRouter) RemoveBindIDRouteURIPlanNameMappingArgsForCall(i int) string {
	fake.removeBindIDRouteURIPlanNameMappingMutex.RLock()
	defer fake.removeBindIDRouteURIPlanNameMappingMutex.RUnlock()
	return fake.removeBindIDRouteURIPlanNameMappingArgsForCall[i].bindID
}

func (fake *FakeRouter) GetRouteURIFromBindID(bindID string) string {
	fake.getRouteURIFromBindIDMutex.Lock()
	ret, specificReturn := fake.getRouteURIFromBindIDReturnsOnCall[len(fake.getRouteURIFromBindIDArgsForCall)]
	fake.getRouteURIFromBindIDArgsForCall = append(fake.getRouteURIFromBindIDArgsForCall, struct {
		bindID string
	}{bindID})
	fake.recordInvocation("GetRouteURIFromBindID", []interface{}{bindID})
	fake.getRouteURIFromBindIDMutex.Unlock()
	if fake.GetRouteURIFromBindIDStub != nil {
		return fake.GetRouteURIFromBindIDStub(bindID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.getRouteURIFromBindIDReturns.result1
}

func (fake *FakeRouter) GetRouteURIFromBindIDCallCount() int {
	fake.getRouteURIFromBindIDMutex.RLock()
	defer fake.getRouteURIFromBindIDMutex.RUnlock()
	return len(fake.getRouteURIFromBindIDArgsForCall)
}

func (fake *FakeRouter) GetRouteURIFromBindIDArgsForCall(i int) string {
	fake.getRouteURIFromBindIDMutex.RLock()
	defer fake.getRouteURIFromBindIDMutex.RUnlock()
	return fake.getRouteURIFromBindIDArgsForCall[i].bindID
}

func (fake *FakeRouter) GetRouteURIFromBindIDReturns(result1 string) {
	fake.GetRouteURIFromBindIDStub = nil
	fake.getRouteURIFromBindIDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeRouter) GetRouteURIFromBindIDReturnsOnCall(i int, result1 string) {
	fake.GetRouteURIFromBindIDStub = nil
	if fake.getRouteURIFromBindIDReturnsOnCall == nil {
		fake.getRouteURIFromBindIDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getRouteURIFromBindIDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeRouter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addPlansMutex.RLock()
	defer fake.addPlansMutex.RUnlock()
	fake.verifyPlanExistsMutex.RLock()
	defer fake.verifyPlanExistsMutex.RUnlock()
	fake.updateRouteMutex.RLock()
	defer fake.updateRouteMutex.RUnlock()
	fake.addBindIDRouteURIPlanNameMappingMutex.RLock()
	defer fake.addBindIDRouteURIPlanNameMappingMutex.RUnlock()
	fake.removeBindIDRouteURIPlanNameMappingMutex.RLock()
	defer fake.removeBindIDRouteURIPlanNameMappingMutex.RUnlock()
	fake.getRouteURIFromBindIDMutex.RLock()
	defer fake.getRouteURIFromBindIDMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRouter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ f5router.Router = new(FakeRouter)
